name: vue build & deploy ci

on: 
  push:
    branches: 
      - src


jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: build & deploy
      uses: JamesIves/github-pages-deploy-action@master 
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: master
        FOLDER: dist
        BUILD_SCRIPT: yarn install && yarn run build
