name: vue build & deploy ci

on: 
  push:
    branches: 
      - src


jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@src
    - name: build & deploy
      uses: JamesIves/github-pages-deploy-action@master 
    - name: Run a multi-line script
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: master
        FOLDER: build
        BUILD_SCRIPT: npm install && npm run build
